In [34]:
import numpy as np 
import pandas as pd
import os

dirname = os.path.dirname('../data')
file_carbon_tax = os.path.join(dirname, 'Carbon_Tax_Pricing/CPI_Data_DashboardExtract.csv')
file_emisions = os.path.join(dirname, 'historical_emissions/historical_emissions.csv')

In [35]:
df_carbon_tax = pd.read_csv('../data/Carbon_Tax_Pricing/CPI_Data_DashboardExtract.csv')
df_emm = pd.read_csv('../data/historical_emissions/historical_emissions.csv')

In [36]:
df_carbon_tax.head()

,"Data last updated November, 01 2020",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Note: Carbon pricing initiatives are considere...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Name of the initiative,Type,Status,Type of juridiction covered,Jurisdiction covered,World Bank region,Year of implementation,Year of abolishment,GHG emissions covered [MtCO2e],Proportion of global GHG emissions covered,"Government income, previous year",Value [billion US$],Initiatives with overlapping GHG emissions cov...,Covered GHG emissions overlapping with other i...
2,Alberta TIER,ETS,Implemented,Subnational,Alberta,North America,2007,0,131.904,0.002434763,0.367606535,2.783371811,NaN,NaN
3,Alberta carbon tax,Carbon tax,Implemented,Subnational,Alberta,North America,2017,2020,0,0,NaN,0.942533516,NaN,NaN
4,Argentina carbon tax,Carbon tax,Implemented,National,Argentina,Latin America and the Caribbean,2018,0,88.1248,0.00162666,0.179263216,0.180258345,NaN,NaN

In [37]:
df_emm["Sector"]

0       Total including LUCF
1       Total excluding LUCF
2                     Energy
3           Electricity/Heat
4       Total excluding LUCF
                ...
2703      Fugitive Emissions
2704      Fugitive Emissions
2705      Fugitive Emissions
2706      Fugitive Emissions
2707      Fugitive Emissions
Name: Sector, Length: 2708, dtype: object

In [38]:
df_emm[df_emm['Country']== 'World'].groupby(['Sector']).sum()

,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
Sector,,,,,,,,,,,,,,,,,,,,,
Agriculture,5884.97,5795.51,5742.44,5678.15,5633.18,5693.47,5678.14,5542.99,5467.33,5473.29,...,5089.10,5034.79,4980.67,5050.88,5057.44,5000.42,4962.59,4991.32,5013.56,5029.15
Building,2796.01,2737.47,2689.70,2660.70,2712.17,2599.00,2654.66,2707.44,2653.97,2704.71,...,2533.91,2463.09,2615.10,2637.75,2566.84,2492.94,2574.50,2514.52,2622.04,2596.85
Bunker Fuels,1001.55,956.89,936.09,908.21,891.50,877.08,878.17,853.81,818.22,849.85,...,748.05,731.97,724.80,667.29,692.11,664.89,644.45,644.42,654.20,657.86
Electricity/Heat,15167.36,14949.51,15009.83,15232.52,15320.55,15059.19,14755.36,14151.17,13257.85,13457.77,...,10134.66,10080.66,9853.19,9586.39,9231.22,9042.50,8945.80,8894.60,8735.04,8596.17
Energy,36435.64,35970.69,35951.84,36053.93,35997.40,35390.08,34998.41,34064.92,32205.11,32624.44,...,25236.65,25085.99,24925.72,24544.78,24048.52,23464.22,23432.23,23345.54,23506.23,23363.95
Fugitive Emissions,2776.00,2779.85,2775.41,2877.38,2860.38,2853.29,2830.66,2793.84,2739.15,2746.40,...,2089.09,2076.10,2091.65,2106.34,2073.70,2063.05,2129.69,2165.36,2261.86,2253.38
Industrial Processes,2825.88,2768.08,2678.62,2671.42,2556.16,2450.41,2371.51,2223.08,2089.21,2039.58,...,1329.14,1323.48,1319.75,1277.11,1225.10,1151.62,1044.44,1030.40,1014.31,1010.44
Land-Use Change and Forestry,3217.07,3217.07,3912.40,3576.82,3366.68,3466.95,3400.35,3341.70,3691.12,3369.51,...,3697.77,4071.09,4637.86,3671.01,4196.67,4196.66,4196.65,4196.62,4196.65,4196.64
Manufacturing/Construction,6174.41,6188.61,6315.81,6360.38,6324.16,6332.91,6313.54,6087.72,5547.26,5563.14,...,3694.74,3854.06,3852.36,3827.31,3937.60,3711.41,3694.80,3743.48,3875.91,3955.39
Other Fuel Combustion,1443.42,1437.09,1444.08,1424.61,1406.72,1363.57,1317.61,1312.84,1282.79,1289.81,...,1191.82,1180.80,1203.74,1154.63,1214.26,1262.92,1293.13,1274.10,1362.83,1353.12
Total excluding LUCF,46730.35,46095.12,45916.49,45917.75,45670.78,45010.58,44515.36,43296.13,41215.92,41584.22,...,33119.37,32910.54,32700.50,32351.08,31807.57,31087.22,30883.65,30785.53,30929.27,30767.94
Total including LUCF,49947.42,49312.19,49828.88,49494.56,49037.46,48477.53,47915.71,46637.83,44907.04,44953.73,...,36817.13,36981.63,37338.36,36022.10,36004.23,35283.88,35080.30,34982.15,35125.92,34964.58
Transportation,8078.45,7878.14,7717.01,7498.34,7373.42,7182.12,7126.58,7011.93,6724.10,6862.60,...,5592.43,5431.29,5309.68,5232.37,5024.90,4891.40,4794.31,4753.49,4648.55,4609.04
Waste,1583.86,1560.85,1543.59,1514.26,1484.04,1476.63,1467.31,1465.13,1454.29,1446.93,...,1464.47,1466.28,1474.36,1478.31,1476.51,1470.96,1444.39,1418.28,1395.18,1364.40

In [39]:
df_emm[df_emm['Country']== 'World']

,Country,Data source,Sector,Gas,Unit,2017,2016,2015,2014,2013,...,1999,1998,1997,1996,1995,1994,1993,1992,1991,1990
0,World,CAIT,Total including LUCF,All GHG,MtCO₂e,49947.42,49312.19,49828.88,49494.56,49037.46,...,36817.13,36981.63,37338.36,36022.10,36004.23,35283.88,35080.30,34982.15,35125.92,34964.58
1,World,CAIT,Total excluding LUCF,All GHG,MtCO₂e,46730.35,46095.12,45916.49,45917.75,45670.78,...,33119.37,32910.54,32700.50,32351.08,31807.57,31087.22,30883.65,30785.53,30929.27,30767.94
2,World,CAIT,Energy,All GHG,MtCO₂e,36435.64,35970.69,35951.84,36053.93,35997.40,...,25236.65,25085.99,24925.72,24544.78,24048.52,23464.22,23432.23,23345.54,23506.23,23363.95
3,World,CAIT,Electricity/Heat,All GHG,MtCO₂e,15167.36,14949.51,15009.83,15232.52,15320.55,...,10134.66,10080.66,9853.19,9586.39,9231.22,9042.50,8945.80,8894.60,8735.04,8596.17
7,World,CAIT,Transportation,All GHG,MtCO₂e,8078.45,7878.14,7717.01,7498.34,7373.42,...,5592.43,5431.29,5309.68,5232.37,5024.90,4891.40,4794.31,4753.49,4648.55,4609.04
8,World,CAIT,Manufacturing/Construction,All GHG,MtCO₂e,6174.41,6188.61,6315.81,6360.38,6324.16,...,3694.74,3854.06,3852.36,3827.31,3937.60,3711.41,3694.80,3743.48,3875.91,3955.39
9,World,CAIT,Agriculture,All GHG,MtCO₂e,5884.97,5795.51,5742.44,5678.15,5633.18,...,5089.10,5034.79,4980.67,5050.88,5057.44,5000.42,4962.59,4991.32,5013.56,5029.15
17,World,CAIT,Land-Use Change and Forestry,All GHG,MtCO₂e,3217.07,3217.07,3912.40,3576.82,3366.68,...,3697.77,4071.09,4637.86,3671.01,4196.67,4196.66,4196.65,4196.62,4196.65,4196.64
20,World,CAIT,Industrial Processes,All GHG,MtCO₂e,2825.88,2768.08,2678.62,2671.42,2556.16,...,1329.14,1323.48,1319.75,1277.11,1225.10,1151.62,1044.44,1030.40,1014.31,1010.44
21,World,CAIT,Building,All GHG,MtCO₂e,2796.01,2737.47,2689.70,2660.70,2712.17,...,2533.91,2463.09,2615.10,2637.75,2566.84,2492.94,2574.50,2514.52,2622.04,2596.85
22,World,CAIT,Fugitive Emissions,All GHG,MtCO₂e,2776.00,2779.85,2775.41,2877.38,2860.38,...,2089.09,2076.10,2091.65,2106.34,2073.70,2063.05,2129.69,2165.36,2261.86,2253.38
31,World,CAIT,Waste,All GHG,MtCO₂e,1583.86,1560.85,1543.59,1514.26,1484.04,...,1464.47,1466.28,1474.36,1478.31,1476.51,1470.96,1444.39,1418.28,1395.18,1364.40
32,World,CAIT,Other Fuel Combustion,All GHG,MtCO₂e,1443.42,1437.09,1444.08,1424.61,1406.72,...,1191.82,1180.80,1203.74,1154.63,1214.26,1262.92,1293.13,1274.10,1362.83,1353.12
42,World,CAIT,Bunker Fuels,All GHG,MtCO₂e,1001.55,956.89,936.09,908.21,891.50,...,748.05,731.97,724.80,667.29,692.11,664.89,644.45,644.42,654.20,657.86

In [ ]:
try:
    df_carbon_tax['Price_Per_Ton_USD'] = df_carbon_tax['Value [billion US$]']*1000/df_carbon_tax['GHG emissions covered [MtCO2e]']
except ZeroDivisionError:
     df_carbon_tax['Price_Per_Ton_USD'] = np.nan

In [ ]:
df_carbon_tax['Price_Per_Ton_USD']

In [ ]:
df_carbon_tax['Price_Per_Ton_USD'] = np.where(df_carbon_tax['Price_Per_Ton_USD'] == np.inf, np.nan,df_carbon_tax['Price_Per_Ton_USD'] )
df_carbon_tax['Price_Per_Ton_USD']

np.sum(df_carbon_tax['Price_Per_Ton_USD'].notna())/df_carbon_tax.shape[0]

In [ ]:
df_carbon_tax['Price_Per_Ton_USD'].mean()

In [ ]:
df_carbon_tax[df_carbon_tax['Status']== 'Under consideration'].head()

country_region = df_carbon_tax.groupby(['Jurisdiction covered','World Bank region'], as_index=False).sum()
reg_mean = country_region.groupby('World Bank region',as_index=False ).mean()
reg_mean

In [ ]:
reg_mean['Price_Per_Ton_USD'][reg_mean['World Bank region']== 'East Asia & Pacific ']

In [ ]:
country_region

In [ ]:
(country_region['Price_Per_Ton_USD']==0) & (country_region['World Bank region']== 'East Asia & Pacific ')

In [ ]:
avg_reg_price = {}

for region in list(reg_mean['World Bank region']):
    
    avg_reg_price[region] =  float(reg_mean['Price_Per_Ton_USD'][reg_mean['World Bank region'] == region])

avg_reg_price['Europe and Central Asia']

In [ ]:
for region in avg_reg_price:
    
    country_region['Price_Per_Ton_USD'+region] = np.where((country_region['Price_Per_Ton_USD']==0) \
                                                   & (country_region['World Bank region']== region),\
                                                 avg_reg_price[region], 0)
    
country_region

In [ ]:
price_columns = ['Price_Per_Ton_USDEast Asia & Pacific ',
       'Price_Per_Ton_USDEurope and Central Asia',
       'Price_Per_Ton_USDLatin America and the Caribbean  ',
       'Price_Per_Ton_USDNorth America',
       'Price_Per_Ton_USDSub-Saharan Africa']

for col in price_columns:
    
    
    country_region['Price_Per_Ton_USD'] += country_region[col]
    

np.sum(country_region['Price_Per_Ton_USD'].isna())

In [ ]:
country_region[country_region['World Bank region']== 'North America']

In [ ]:
df_em

In [ ]:
df_em.columns

In [ ]:
sector_em = df_emm.groupby(['Sector'], as_index=False).sum()
sector_em

In [ ]:
total_2017 = float((sector_em['2017'][sector_emm['Sector']== 'Total including LUCF']))
sector_em['Percent_2017'] = sector_em['2017']/total_2017
# sector_emm
total_2017

In [ ]:
sector_em.sort_values(by='Percent_2017', ascending=False)

In [ ]:
sum(sector_em['Percent_2017'])

In [33]:
import os
import requests

ModuleNotFoundError: No module named 'requests'

In [ ]:
url = 'https://www.quandl.com/api/v3/datasets/CHRIS/ICE_C1.csv?api_key=-q3ecFz_jdpZBNM73ozq'

In [ ]:
def em_cost: